### ISSUE TITLE
P2P to Code Review

### ISSUE THREAD

**Issue by Lul-Abdifan** [microvese-projects/Portfolio#19]
### Portfolio Peer Code Review
Hello @Bennyjoez, You did an amazing but there is some issue  you have  to do it 

- Could you please add Some padding under your popup image container
- Optionally: Kindly add a scroll snap to the images contained in the project details popup.

We hope You will fix it. Thank you for your openness . We appreciate you.

**Comment by Bennyjoez** [comment]
Issues fixed and committed
