### ISSUE TITLE
Peer-to-Peer Code Review

### ISSUE THREAD

**Issue by skabeo** [microvese-projects/Portfolio#20]
Hi @Bennyjoez 

<img src="https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif">

**Good job implementing the project requirement but there are some changes required**

- Kindly make the project image container responsive on smaller screens (screen size less than 375px)

**Comment by Bennyjoez** [comment]
Thank you for the review guys I will work on implementing the changes. 😄

**Comment by Bennyjoez** [comment]
Issues fixed and committed.
